name: jaffle_shop_2

profile: jaffle_shop_2

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  jaffle_shop_2:
    +schema: raw

models:
  jaffle_shop_2:
    staging:
      silver_technical:
        +materialized: view
        +schema: SILVER_TECHNICAL

      silver_business:
        +materialized: table
        +schema: SILVER_BUSINESS

    marts:
      gold_layer:
        +materialized: table
        +schema: GOLD

snapshots:
  jaffle_shop_2:
    +target_schema: SNAPSHOTS
